# Generated by Django 6.1.1 on 2026-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кому дарує')),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
